# Decoherence and Quantum Noise

One of the biggest practical problems in quantum computing is that quantum states are extremely fragile.

Real quantum systems constantly interact with their environments through:
- heat
- vibrations
- electromagnetic interference
- unintended physical interactions

These interactions disturb the quantum state and gradually destroy quantum behavior.

# Decoherence

Decoherence is the process through which a quantum system loses its coherent quantum properties because of environmental interaction.

Measurement collapse feels like something caused intentionally during observation, but the environment itself can behave like a measurement system.

Superposition and entanglement degrade as quantum information leaks into the environment.

# Why This Is Dangerous

Quantum algorithms depend heavily on:
- interference
- stable phase relationships
- coherent superposition
- preserved entanglement

Noise and decoherence damage these properties.

As decoherence increases, the system begins behaving more classically and quantum computational advantages weaken.

Without error correction, fragile quantum information would decay too quickly for large computations to finish.

In [2]:
from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator
from qiskit_aer.noise import NoiseModel, pauli_error

# create noise model
noise_model = NoiseModel()

# create bit-flip error
error = pauli_error([('X', 0.3), ('I', 0.7)])

# apply noise to identity operation
noise_model.add_all_qubit_quantum_error(error, ['id'])

# create circuit
qc = QuantumCircuit(1,1)

# keep qubit in |0>
qc.id(0)

# measurement
qc.measure(0,0)

# draw circuit
print(qc.draw())

# noisy simulator
simulator = AerSimulator(noise_model=noise_model)

# run
job = simulator.run(qc, shots=1000)

result = job.result()
counts = result.get_counts()

print(counts)

     ┌───┐┌─┐
  q: ┤ I ├┤M├
     └───┘└╥┘
c: 1/══════╩═
           0 
{'1': 305, '0': 695}


# Observation

I intentionally kept the qubit in the state |0> instead of creating superposition.

An identity gate I was applied, which ideally should not change the qubit state at all.

Without noise, the expected output would therefore be {'0': 1000} because the qubit should remain completely stable in |0> throughout the computation.

However, the noisy simulator introduced random bit-flip errors using X gate with probability 30%

This meant that during the computation, some qubits were randomly flipped from 0 to 1.

As a result, the measured output became approximately: {'0': 695, '1': 305} (first run)